#
# print("aa", "bb", "OO", sep="****", end="")
# print("dd", "cc")
# print('Мы изучаем язык Python')
# print('g', "d", 'f')
# print('Скоро я', 'исправлю физику', 'на 8')
# a = "hello, world"
# print(a)
# print(4)
# print(8)
# print(15)
# print(16)
# print(23)
# print(42)
#
# print("важные изученные команды за сегодня -?")
# input()
# print("главная трудность - ?")
# input()
# print("пайтон хороший язык для игр ?")
# input()
# print("лучшая часть занятия - ?")
# input()
# print("лучшая часть пайтона?")
# input()
