# a = float(input())
# b = a / 2
# print(b)
# num1 = int('123')
# num2 = int('2')
# print(num1 + num2)
# num1 = float('-0.5')
# num2 = float('6')
# print(num1 + num2)
# num1 = float('2.0')
# num2 = float('5 + 5')
# print(num2 - num1)
# num1 = float(3.0)
# num2 = float(2 - 2)
# print(num1 * num2)
# print(25_000)
# print(25_000 == 25000)
# a = float(input())
# b = float(input())
# c = 0.5 * a * b
# print(c)
# a = float(input())
# b = 5 / 9 * (a - 32)
# print(b)
# a = float(input())
# c = int(a * 10 % 10)
# print(c)
# num = max(1, 3, -5, 7) + min (-3, 6, -8, -1) + abs(-17)
# print(num)
# a = int(input())
# b = int(input())
# c = int(input())
# v = max(a, b, c)
# n = min(a, b, c)
# print(max(a, b, c))
# print(abs((a + b + c) - (v + n)))
# print(min(a, b, c))
# a1 = float(input())
# a2 = float(input())
# a3 = float(input())
# a4 = float(input())
# a5 = float(input())
# b = abs(a1) + abs(a2) + abs(a3) + abs(a4) + abs(a5)
# print(b)
# str1 = '1'
# str2 = str1 + '2' + str1
# str3 = str2 + '3' + str2
# str4 = str3 + '4' + str3
# print(str4)
# a = input()
# b = len(a)
# print('футбольная команда', a, 'имеет длину', b, 'символов')
# a = input()
# b = input()
# c = input()
# v = len(a)
# n = len(b)
# m = len(c)
# t = max(v, n, m)
# y = min(v, n, m)
# if t == v:
#     print(a)
# if t == n:
#     print(b)
# if t == m:
#     print(c)
# if y == v:
#     print(a)
# if y == n:
#     print(b)
# if y == m:
#     print(c)
